export enum constants {
    AUTH_REQUEST = 'AUTH/AUTH_REQUEST',
    SUCCESS_REQUEST = 'AUTH/SUCCESS_REQUEST',
    FAIL_REQUEST = 'AUTH/FAIL_REQUEST',
    SET_CURRENT_USER = 'AUTH/SET_CURRENT_USER',
    USER_LOGOUT = 'AUTH/USER_LOGOUT',
}